version: '3.8'
services:
  auth-service:
    build: ../auth-service
    container_name: pje_auth_service
    ports:
      - '3001:3001'
  api-gateway:
    build: ../api-gateway
    container_name: pje_api_gateway
    ports:
      - '3000:3000'
    depends_on:
      - auth-service
  operator-ui:
    build: ../operator-ui
    container_name: pje_operator_ui
    ports:
      - '3002:3002'
    depends_on:
      - api-gateway
  worker:
    build: ../worker
    container_name: pje_worker
    depends_on:
      - api-gateway
